/*
#include <algorithm> //OK
#include <bitset> //OK
#include <complex> //OK
#include <deque> //OK
#include <exception> //OK
#include <fstream> //OK
#include <functional> //OK
#include <iomanip> //OK
#include <ios> //OK
#include <iosfwd> //OK
#include <istream> //OK
#include <iterator> //OK
#include <limits> //OK
#include <list> //OK
#include <locale> //OK
#include <map> //OK
#include <memory> //OK
#include <new> //OK
#include <numeric> //OK
#include <ostream> //OK
#include <queue> //OK
#include <set> //OK
#include <sstream> //OK
#include <stack> //OK
#include <stdexcept> //OK
#include <streambuf> //OK
#include <string> //OK
#include <typeinfo> //OK
#include <utility> //OK
#include <valarray> //OK
#include <vector> //OK
*/
