/*
Socoa - Source Code Analysis Library
Copyright © 2008, 2009  Florian Goujeon

This file is part of Socoa.

Socoa is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

Socoa is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with Socoa.  If not, see <http://www.gnu.org/licenses/>.
*/

#ifndef SOCOA_CPP_PARSE_TREE_TO_SYNTAX_TREE_NODE_CONVERTERS_HPP
#define SOCOA_CPP_PARSE_TREE_TO_SYNTAX_TREE_NODE_CONVERTERS_HPP

#include <string>
#include "../grammar.hpp"
#include "../syntax_tree.hpp"
#include "conversion_functions.hpp"
#include "special_conversion_functions_fwd.hpp"

#define SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_ID_SPECIALIZATION(id, return_type, convert_function)\
template<class T>																				\
struct node_converter_from_id<T, grammar::parser_id::id>										\
{																								\
	static																						\
	syntax_nodes::return_type																	\
	convert(const tree_node_t& node)															\
	{																							\
		return convert_##convert_function(node);												\
	}																							\
};

#define SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_TYPE_SPECIALIZATION(return_type, convert_function)\
template<>																						\
struct node_converter_from_type<syntax_nodes::return_type>										\
{																								\
	static																						\
	syntax_nodes::return_type																	\
	convert(const tree_node_t& node)															\
	{																							\
		return convert_##convert_function(node);												\
	}																							\
};

#define SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION(id, return_type, convert_function)\
SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_ID_SPECIALIZATION(id, return_type, convert_function)\
SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_TYPE_SPECIALIZATION(return_type, convert_function)

namespace socoa { namespace cpp { namespace parse_tree_to_syntax_tree
{

/**
Calls the convert_* function corresponding to the given grammar's parser id.
*/
template<class T, int ParserId>
struct node_converter_from_id;

/**
Calls the convert_* function corresponding to the given syntax node type.
*/
template<class T>
struct node_converter_from_type;

//specialization for sequences
template<class T>
struct node_converter_from_type
{
	static
	T
	convert(const tree_node_t& node)
	{
		return convert_sequence<T>(node);
	}
};

//specialization for string enumerations
template<const std::vector<std::string>& StringList>
struct node_converter_from_type<syntax_nodes::string_enumeration_node<StringList>>
{
	static
	syntax_nodes::string_enumeration_node<StringList>
	convert(const tree_node_t& node)
	{
		return convert_string_enumeration<syntax_nodes::string_enumeration_node<StringList>>(node);
	}
};

//other specializations
//SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION(id::ASM_DEFINITION,
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ASSIGNMENT_EXPRESSION,
	assignment_expression,
	assignment_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ASSIGNMENT_EXPRESSION_CONDITION,
	assignment_expression_condition,
	assignment_expression_condition
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ASSIGNMENT_EXPRESSION_FIRST_PART,
	assignment_expression::first_part,
	assignment_expression_first_part
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	BASE_CLAUSE,
	base_clause,
	base_clause
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_TYPE_SPECIALIZATION
(
	base_specifier,
	base_specifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	BLOCK_DECLARATION,
	block_declaration,
	block_declaration
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	BOOLEAN_LITERAL,
	boolean_literal,
	boolean_literal
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	BRACKETED_INITIALIZER,
	bracketed_initializer,
	bracketed_initializer
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	BREAK_STATEMENT,
	break_statement,
	break_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	BUILT_IN_TYPE_SPECIFIER,
	built_in_type_specifier,
	string_enumeration<syntax_nodes::built_in_type_specifier>
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CAST_EXPRESSION,
	cast_expression,
	cast_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CHARACTER_LITERAL,
	character_literal,
	character_literal
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CLASS_HEAD,
	class_head,
	class_head
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CLASS_SPECIFIER,
	class_specifier,
	class_specifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	COMPOUND_STATEMENT,
	compound_statement,
	compound_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CONDITION,
	condition,
	condition
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CONDITIONAL_EXPRESSION,
	conditional_expression,
	conditional_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CONTINUE_STATEMENT,
	continue_statement,
	continue_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CONVERSION_FUNCTION_ID,
	conversion_function_id,
	conversion_function_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CTOR_INITIALIZER,
	ctor_initializer,
	ctor_initializer
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CV_QUALIFIER,
	cv_qualifier,
	cv_qualifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_TYPE_SPECIALIZATION
(
	decl_specifier,
	decl_specifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DECLARATION,
	declaration,
	declaration
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DECLARATOR,
	declarator,
	declarator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DECLARATOR_ID,
	declarator_id,
	declarator_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DELETE_EXPRESSION,
	delete_expression,
	delete_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DESTRUCTOR_NAME,
	destructor_name,
	destructor_name
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DIRECT_DECLARATOR,
	direct_declarator,
	direct_declarator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DIRECT_DECLARATOR_ARRAY_PART,
	direct_declarator::array_part,
	direct_declarator_array_part
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DIRECT_DECLARATOR_FUNCTION_PART,
	direct_declarator::function_part,
	direct_declarator_function_part
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DIRECT_DECLARATOR_NEXT_PART,
	direct_declarator::next_part,
	direct_declarator_next_part
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DO_WHILE_STATEMENT,
	do_while_statement,
	do_while_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ELABORATED_TYPE_SPECIFIER,
	elaborated_type_specifier,
	elaborated_type_specifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	EMPTY_INITIALIZER_LIST_INITIALIZER_CLAUSE,
	empty_initializer_list_initializer_clause,
	empty_initializer_list_initializer_clause
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	EQUAL_INITIALIZER,
	equal_initializer,
	equal_initializer
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	EXPRESSION,
	expression,
	sequence<syntax_nodes::expression>
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	EXPRESSION_STATEMENT,
	expression_statement,
	expression_statement
)
//            id::EXPLICIT_INSTANTIATION,
//            id::EXPLICIT_SPECIALIZATION,
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	FLOATING_LITERAL,
	floating_literal,
	floating_literal
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	FOR_INIT_STATEMENT,
	for_init_statement,
	for_init_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	FOR_STATEMENT,
	for_statement,
	for_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	FUNCTION_DEFINITION,
	function_definition,
	function_definition
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	FUNCTION_SPECIFIER,
	function_specifier,
	string_enumeration<syntax_nodes::function_specifier>
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	GOTO_STATEMENT,
	goto_statement,
	goto_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ID_EXPRESSION,
	id_expression,
	id_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	IDENTIFIER,
	identifier,
	identifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	IDENTIFIER_OR_TEMPLATE_ID,
	identifier_or_template_id,
	identifier_or_template_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_TYPE_SPECIALIZATION
(
	init_declarator,
	init_declarator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	INITIALIZER,
	initializer,
	initializer
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	INITIALIZER_CLAUSE,
	initializer_clause,
	initializer_clause
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	INITIALIZER_LIST_INITIALIZER_CLAUSE,
	initializer_list_initializer_clause,
	initializer_list_initializer_clause
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	INTEGER_LITERAL,
	integer_literal,
	integer_literal
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ITERATION_STATEMENT,
	iteration_statement,
	iteration_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	JUMP_STATEMENT,
	jump_statement,
	jump_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	LABELED_STATEMENT,
	labeled_statement,
	labeled_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	LITERAL,
	literal,
	literal
)
//            id::LINKAGE_SPECIFICATION,
	//id::NAMESPACE_ALIAS_DEFINITION,
SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_TYPE_SPECIALIZATION
(
	mem_initializer,
	mem_initializer
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	MEM_INITIALIZER_ID,
	mem_initializer_id,
	mem_initializer_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	MEMBER_DECLARATION,
	member_declaration,
	member_declaration
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	MEMBER_DECLARATION_FUNCTION_DEFINITION,
	member_declaration_function_definition,
	member_declaration_function_definition
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	MEMBER_DECLARATION_MEMBER_DECLARATOR_LIST,
	member_declaration_member_declarator_list,
	member_declaration_member_declarator_list
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	MEMBER_DECLARATION_UNQUALIFIED_ID,
	member_declaration_unqualified_id,
	member_declaration_unqualified_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_TYPE_SPECIALIZATION
(
	member_declarator,
	member_declarator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	MEMBER_DECLARATOR_BIT_FIELD_MEMBER,
	member_declarator_bit_field_member,
	member_declarator_bit_field_member
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	MEMBER_DECLARATOR_DECLARATOR,
	member_declarator_declarator,
	member_declarator_declarator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	MEMBER_SPECIFICATION_PART,
	member_specification_part,
	member_specification_part
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	MEMBER_SPECIFICATION_ACCESS_SPECIFIER,
	member_specification_access_specifier,
	member_specification_access_specifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	NAMESPACE_DEFINITION,
	namespace_definition,
	namespace_definition
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	NESTED_IDENTIFIER_OR_TEMPLATE_ID,
	nested_identifier_or_template_id,
	nested_identifier_or_template_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	NESTED_NAME_SPECIFIER,
	nested_name_specifier,
	nested_name_specifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	NESTED_NAME_SPECIFIER_NEXT_PART,
	nested_name_specifier::next_part,
	nested_name_specifier_next_part
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	NEW_EXPRESSION,
	new_expression,
	new_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	OPERATOR_FUNCTION_ID,
	operator_function_id,
	operator_function_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_TYPE_SPECIALIZATION
(
	parameter_declaration,
	parameter_declaration
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	PARAMETER_DECLARATION_CLAUSE,
	parameter_declaration_clause,
	parameter_declaration_clause
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	POSTFIX_EXPRESSION,
	postfix_expression,
	postfix_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	PRIMARY_EXPRESSION,
	primary_expression,
	primary_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	PTR_OPERATOR,
	ptr_operator,
	ptr_operator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	QUALIFIED_ID,
	qualified_id,
	qualified_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	QUALIFIED_NESTED_ID,
	qualified_nested_id,
	qualified_nested_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	QUALIFIED_OPERATOR_FUNCTION_ID,
	qualified_operator_function_id,
	qualified_operator_function_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	QUALIFIED_TEMPLATE_ID,
	qualified_template_id,
	qualified_template_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	QUALIFIED_IDENTIFIER,
	qualified_identifier,
	qualified_identifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	RETURN_STATEMENT,
	return_statement,
	return_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	SELECTION_STATEMENT,
	selection_statement,
	selection_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	SIMPLE_DECLARATION,
	simple_declaration,
	simple_declaration
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	SIMPLE_TYPE_SPECIFIER,
	simple_type_specifier,
	simple_type_specifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	SIMPLE_TEMPLATE_TYPE_SPECIFIER,
	simple_template_type_specifier,
	simple_template_type_specifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	SPACE,
	space,
	space
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	STATEMENT,
	statement,
	statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	STORAGE_CLASS_SPECIFIER,
	storage_class_specifier,
	string_enumeration<syntax_nodes::storage_class_specifier>
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	STRING_LITERAL,
	string_literal,
	string_literal
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_TYPE_SPECIALIZATION
(
	template_argument,
	template_argument
)
/*SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TEMPLATE_ARGUMENT_ASSIGNMENT_EXPRESSION,
	assignment_expression,
	assignment_expression
)*/
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TEMPLATE_DECLARATION,
	template_declaration,
	template_declaration
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TEMPLATE_ID,
	template_id,
	template_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TRANSLATION_UNIT,
	translation_unit,
	translation_unit
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TRY_BLOCK,
	try_block,
	try_block
)
/*SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TYPE_ID,
	type_id,
	type_id
)*/
SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_ID_SPECIALIZATION
(
	TYPE_NAME,
	identifier,
	identifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TYPE_ID_SIZEOF_EXPRESSION,
	type_id_sizeof_expression,
	type_id_sizeof_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TYPE_SPECIFIER,
	type_specifier,
	type_specifier
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	UNARY_EXPRESSION,
	unary_expression,
	unary_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	UNARY_OPERATOR_UNARY_EXPRESSION,
	unary_operator_unary_expression,
	unary_operator_unary_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	UNARY_SIZEOF_EXPRESSION,
	unary_sizeof_expression,
	unary_sizeof_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	UNQUALIFIED_ID,
	unqualified_id,
	unqualified_id
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	USING_DECLARATION,
	using_declaration,
	using_declaration
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	USING_DIRECTIVE,
	using_directive,
	using_directive
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	WHILE_STATEMENT,
	while_statement,
	while_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	POSTFIX_EXPRESSION_FIRST_PART,
	postfix_expression::first_part,
	postfix_expression_first_part
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	SIMPLE_TYPE_SPECIFIER_POSTFIX_EXPRESSION,
	simple_type_specifier_postfix_expression,
	simple_type_specifier_postfix_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TYPENAME_EXPRESSION,
	typename_expression,
	typename_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TEMPLATE_TYPENAME_EXPRESSION,
	template_typename_expression,
	template_typename_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DYNAMIC_CAST_EXPRESSION,
	dynamic_cast_expression,
	dynamic_cast_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	STATIC_CAST_EXPRESSION,
	static_cast_expression,
	static_cast_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	REINTERPRET_CAST_EXPRESSION,
	reinterpret_cast_expression,
	reinterpret_cast_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CONST_CAST_EXPRESSION,
	const_cast_expression,
	const_cast_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TYPEID_EXPRESSION,
	typeid_expression,
	typeid_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TYPE_ID_TYPEID_EXPRESSION,
	type_id_typeid_expression,
	type_id_typeid_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	POSTFIX_EXPRESSION_LAST_PART,
	postfix_expression::last_part,
	postfix_expression_last_part
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	SQUARE_BRACKETED_EXPRESSION,
	square_bracketed_expression,
	square_bracketed_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	BRACKETED_EXPRESSION_LIST,
	bracketed_expression_list,
	bracketed_expression_list
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DOT_ID_EXPRESSION,
	dot_id_expression,
	dot_id_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ARROW_ID_EXPRESSION,
	arrow_id_expression,
	arrow_id_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DOT_PSEUDO_DESTRUCTOR_NAME,
	dot_pseudo_destructor_name,
	dot_pseudo_destructor_name
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ARROW_PSEUDO_DESTRUCTOR_NAME,
	arrow_pseudo_destructor_name,
	arrow_pseudo_destructor_name
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	IF_STATEMENT,
	if_statement,
	if_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	SWITCH_STATEMENT,
	switch_statement,
	switch_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CASE_STATEMENT,
	case_statement,
	case_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DEFAULT_STATEMENT,
	default_statement,
	default_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	CLASSIC_LABELED_STATEMENT,
	classic_labeled_statement,
	classic_labeled_statement
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DOUBLE_PLUS,
	simple_text_node<util::extern_strings::double_plus>,
	simple_text<util::extern_strings::double_plus>
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DOUBLE_MINUS,
	simple_text_node<util::extern_strings::double_minus>,
	simple_text<util::extern_strings::double_minus>
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	THIS_KEYWORD,
	simple_text_node<util::extern_strings::this_>,
	simple_text<util::extern_strings::this_>
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ROUND_BRACKETED_EXPRESSION,
	round_bracketed_expression,
	round_bracketed_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	HANDLER,
	handler,
	handler
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	THROW_EXPRESSION,
	throw_expression,
	throw_expression
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	EXCEPTION_DECLARATION,
	exception_declaration,
	exception_declaration
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	EXCEPTION_DECLARATOR,
	exception_declarator,
	exception_declarator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	EXCEPTION_ABSTRACT_DECLARATOR,
	exception_abstract_declarator,
	exception_abstract_declarator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ELLIPSIS,
	simple_text_node<util::extern_strings::ellipsis>,
	simple_text<util::extern_strings::ellipsis>
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	TYPE_SPECIFIER_SEQ,
	type_specifier_seq,
	sequence<syntax_nodes::type_specifier_seq>
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DIRECT_ABSTRACT_DECLARATOR,
	direct_abstract_declarator,
	direct_abstract_declarator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	PTR_OPERATOR_SEQ,
	ptr_operator_seq,
	sequence<syntax_nodes::ptr_operator_seq>
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ABSTRACT_DECLARATOR,
	abstract_declarator,
	abstract_declarator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	FUNCTION_TRY_BLOCK,
	function_try_block,
	function_try_block
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	OPERATOR,
	operator_,
	operator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	ARRAY_OPERATOR,
	array_operator,
	array_operator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	NEW_ARRAY_OPERATOR,
	new_array_operator,
	new_array_operator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	DELETE_ARRAY_OPERATOR,
	delete_array_operator,
	delete_array_operator
)
SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
(
	SIMPLE_OPERATOR,
	simple_operator,
	string_enumeration<syntax_nodes::simple_operator>
)

template<class SyntaxNodeT>
inline
SyntaxNodeT
convert_node(const tree_node_t& node)
{
	return node_converter_from_type<SyntaxNodeT>::convert(node);
}

}}} //namespace socoa::cpp::parse_tree_to_syntax_tree

#undef SOCOA_CPP_GENERATE_NODE_CONVERTER_SPECIALIZATION
#undef SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_ID_SPECIALIZATION
#undef SOCOA_CPP_GENERATE_NODE_CONVERTER_FROM_TYPE_SPECIALIZATION

#endif
