char               v01;
unsigned char      v02;
signed char        v03;
bool               v04;
unsigned           v05;
unsigned int       v06;
signed             v07;
signed int         v08;
int                v09;
unsigned short int v10;
unsigned short     v11;
unsigned long int  v12;
unsigned long      v13;
signed long int    v14;
signed long        v15;
long int           v16;
long               v17;
signed short int   v18;
signed short       v19;
short int          v20;
short              v21;
wchar_t            v22;
float              v23;
double             v24;
long double        v25;
void*              v26;

